<?php

/**
 * @file
 * Initiate dev site.
 */

/**
 * Implements hook_install().
 */
function amp_dev_install() {
  $this_user = \Drupal::entityTypeManager()->getStorage('user')->load(100);
  $this_user->set('field_user_first_name', 'Julie');
  $this_user->set('field_user_last_name', 'Ma');
  $this_user->set('field_institution', 'MGHPCC');
  $this_user->save();
  \Drupal::service('module_installer')->uninstall(['captcha','image_captcha', 'recaptcha']);
  // Disable constant contact cron run.
  \Drupal::state()->set('access_affinitygroup.alloc_cron_disable', TRUE);
}
